# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$PATH"

# Expand ! commands
bind Space:magic-space

command -v pyenv &> /dev/null && eval "$(pyenv init -)"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/cschmitz/.sdkman"
[[ -s "/Users/cschmitz/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/cschmitz/.sdkman/bin/sdkman-init.sh"
