alias .aco='$EDITOR $HOME/.aws/{config,credentials}'
alias .g='$EDITOR $HOME/.gitconfig'
alias .l='$EDITOR $HOME/.localrc'
alias .sshc='$EDITOR $HOME/.ssh/config'
alias .sshh='$EDITOR $HOME/.ssh/known_hosts'
alias .v='$EDITOR $HOME/.vimrc'
alias .z='$EDITOR $HOME/.zshrc'

alias cddl='cd $HOME/Downloads'
alias cddt='cd $HOME/Desktop'
alias cdot='cd $HOME/dotfiles'
alias cddot='cd $HOME/dotfiles'
alias cdvim='cd $HOME/.vim'

alias envs='env | sort'
alias g='git'
alias grep='grep --color'
alias gw='./gradlew'
alias gwn='./gradlew --no-daemon'
alias h='history'
alias hosts='sudo $EDITOR /etc/hosts'
alias lsm2='ls ~/.m2/repository'
alias myps='ps -ef | grep $USER'
alias mw='./mvnw'
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"
alias reload!='. ~/.zshrc'
alias rlr='rlwrap -a -- redis-cli'
alias s='source $HOME/.bash_profile'
alias tf='terraform'
alias toxi='toxiproxy-cli'

alias u='cd ..'
alias u2='cd ../..'
alias u3='cd ../../..'
alias u4='cd ../../../..'
alias u5='cd ../../../../..'
alias u6='cd ../../../../../..'
alias u7='cd ../../../../../../..'
